[metadata]
name = continual_learning_for_very_short_term_load_forecastin_a_case_study_on_parts_cleaning
version = 1.0.0
author = Robin Zink
author_email = r.zink@ptw.tu-darmstadt.de
url = eta-fabrik.de
description = Continual learning library for neural networks
long_description = file: README.md
keywords = machine learning, data science, continual learning
license = MIT License
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11

[options]
include_package_data = True
packages = find_namespace:
install_requires =
    pandas<=2.0.2
    numpy<=1.24.3
    scikit-learn<=1.2.2
    statsmodels<=0.14.0
    scipy<=1.10.1
    hyperopt<=0.27
    seaborn<=0.12.2
    matplotlib<=3.7.1
    bokeh==2.4.3
    keras_pickle_wrapper<=1.0.5
    tensorflow<=2.9.1
    pydantic<=1.10.9
    autokeras<=1.0.19

[options.package_data]
* = *.md

[flake8]
max-line-length = 120
